import { Member } from '@/types/member';
import { Event } from '@/types/event';

export const MOCK_EVENTS: Event[] = [
  {
    id: 'e1',
    title: 'Youth Leadership Summit 2026',
    description: 'A comprehensive training for youth leaders across the union mission.',
    category: 'TRAINING',
    status: 'UPCOMING',
    startDate: '2026-06-15T09:00:00',
    endDate: '2026-06-17T17:00:00',
    location: 'Kigali Convention Centre',
    organizer: 'Union Youth Department',
    maxAttendees: 500,
    currentAttendees: 342,
    imageUrl: 'https://images.unsplash.com/photo-1540575861501-7cf05a4b125a?q=80&w=2070&auto=format&fit=crop',
    timeline: [
      { id: 't1', time: '09:00', activity: 'Opening Ceremony', description: 'Welcome address and keynote speaker.' },
      { id: 't2', time: '11:00', activity: 'Workshop A', description: 'Leadership principles in the digital age.' },
      { id: 't3', time: '14:00', activity: 'Panel Discussion', description: 'Challenges facing modern youth.' },
    ],
    attendance: [],
  },
  {
    id: 'e2',
    title: 'Regional Worship Festival',
    description: 'Celebrating our faith through music and testimony.',
    category: 'WORSHIP',
    status: 'ONGOING',
    startDate: '2026-05-18T10:00:00',
    endDate: '2026-05-18T20:00:00',
    location: 'Amahoro Stadium',
    organizer: 'Central Rwanda Field',
    maxAttendees: 5000,
    currentAttendees: 4200,
    imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=2070&auto=format&fit=crop',
    timeline: [
      { id: 't4', time: '10:00', activity: 'Opening Hymns', description: 'Combined choirs performance.' },
      { id: 't5', time: '12:00', activity: 'Sermonette', description: 'Theme: Faith in Action.' },
    ],
    attendance: [
      { memberId: '1', memberName: 'Jean Niyomugabo', status: 'PRESENT', registeredAt: '2026-05-18T10:15:00' },
      { memberId: '2', memberName: 'Marie Uwimana', status: 'PRESENT', registeredAt: '2026-05-18T10:30:00' },
    ],
  },
  {
    id: 'e3',
    title: 'Health & Wellness Seminar',
    description: 'Promoting a healthy lifestyle in our community.',
    category: 'COMMUNITY',
    status: 'COMPLETED',
    startDate: '2026-05-10T14:00:00',
    endDate: '2026-05-10T18:00:00',
    location: 'Gisenyi North Church',
    organizer: 'West Rwanda Field',
    maxAttendees: 200,
    currentAttendees: 185,
    imageUrl: 'https://images.unsplash.com/photo-1505373633560-fa91176bc2ed?q=80&w=2070&auto=format&fit=crop',
    timeline: [
      { id: 't6', time: '14:00', activity: 'Health Screening', description: 'Free blood pressure and sugar checks.' },
      { id: 't7', time: '16:00', activity: 'Nutrition Talk', description: 'Plant-based diet benefits.' },
    ],
    attendance: [
      { memberId: '2', memberName: 'Marie Uwimana', status: 'PRESENT', registeredAt: '2026-05-10T14:10:00' },
      { memberId: '4', memberName: 'Alice Mutoni', status: 'ABSENT' },
    ],
  },
  {
    id: 'e4',
    title: 'Union Evangelism Conference',
    description: 'Annual evangelism planning and outreach training for all fields.',
    category: 'CONFERENCE',
    status: 'UPCOMING',
    startDate: '2026-07-22T08:00:00',
    endDate: '2026-07-24T16:00:00',
    location: 'Adventist University of Central Africa',
    organizer: 'Rwanda Union Mission',
    maxAttendees: 800,
    currentAttendees: 156,
    imageUrl: 'https://images.unsplash.com/photo-1475721027785-f74eccf83e33?q=80&w=2070&auto=format&fit=crop',
    timeline: [
      { id: 't8', time: '08:00', activity: 'Registration', description: 'Badge pickup and networking breakfast.' },
      { id: 't9', time: '10:00', activity: 'Keynote', description: 'Mission vision for 2026–2030.' },
      { id: 't10', time: '14:00', activity: 'Field Breakouts', description: 'Regional strategy sessions.' },
    ],
    attendance: [],
  },
  {
    id: 'e5',
    title: 'Sabbath School Teachers Workshop',
    description: 'Equipping teachers with new curriculum tools and discussion methods.',
    category: 'TRAINING',
    status: 'UPCOMING',
    startDate: '2026-05-25T14:00:00',
    endDate: '2026-05-25T17:30:00',
    location: 'Kigali Central Church',
    organizer: 'Sabbath School Department',
    maxAttendees: 120,
    currentAttendees: 89,
    imageUrl: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?q=80&w=2070&auto=format&fit=crop',
    timeline: [
      { id: 't11', time: '14:00', activity: 'Curriculum Overview', description: 'Quarterly lesson structure.' },
      { id: 't12', time: '16:00', activity: 'Practical Demo', description: 'Interactive class simulation.' },
    ],
    attendance: [],
  },
  {
    id: 'e6',
    title: 'Field Auditor Meeting Q1',
    description: 'Quarterly financial and administrative review for field auditors.',
    category: 'OTHER',
    status: 'COMPLETED',
    startDate: '2026-04-28T09:00:00',
    endDate: '2026-04-28T15:00:00',
    location: 'Union Headquarters',
    organizer: 'Treasury Department',
    maxAttendees: 50,
    currentAttendees: 45,
    imageUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=2070&auto=format&fit=crop',
    timeline: [
      { id: 't13', time: '09:00', activity: 'Opening Devotion', description: 'Stewardship reflection.' },
      { id: 't14', time: '11:00', activity: 'Audit Reports', description: 'Field-by-field presentations.' },
    ],
    attendance: [
      { memberId: '3', memberName: 'Samuel Mugisha', status: 'PRESENT', registeredAt: '2026-04-28T09:05:00' },
    ],
  },
];

const generateActivities = (id: string) => [
  { id: `a1-${id}`, type: 'BAPTISM' as const, description: 'Baptized into the SDA Church', date: '2015-08-22', performedBy: 'Pr. Muvunyi' },
  { id: `a2-${id}`, type: 'ROLE_CHANGE' as const, description: 'Assigned as Youth Leader', date: '2020-01-10', performedBy: 'Admin' },
  { id: `a3-${id}`, type: 'NOTE' as const, description: 'Transferred from Eastern Field', date: '2022-05-15', performedBy: 'System' },
];

export const MOCK_MEMBERS: Member[] = [
  {
    id: '1',
    firstName: 'Jean',
    lastName: 'Niyomugabo',
    email: 'jean.n@example.com',
    phone: '+250 788 000 001',
    role: 'CHURCH_LEADER',
    status: 'ACTIVE',
    churchName: 'Kigali Central Church',
    zoneName: 'Kigali City Zone',
    fieldName: 'Central Rwanda Field',
    unionName: 'Rwanda Union Mission',
    baptismDate: '2010-05-15',
    joinDate: '2010-06-01',
    address: 'KN 45 St, Kigali',
    gender: 'MALE',
    dateOfBirth: '1985-03-20',
    activities: generateActivities('1'),
  },
  {
    id: '2',
    firstName: 'Marie',
    lastName: 'Uwimana',
    email: 'm.uwimana@example.com',
    phone: '+250 788 000 002',
    role: 'MEMBER',
    status: 'ACTIVE',
    churchName: 'Gisenyi North Church',
    zoneName: 'Rubavu Zone',
    fieldName: 'West Rwanda Field',
    unionName: 'Rwanda Union Mission',
    baptismDate: '2015-08-22',
    joinDate: '2015-09-10',
    address: 'Rubavu, Gisenyi',
    gender: 'FEMALE',
    dateOfBirth: '1992-11-12',
    activities: generateActivities('2'),
  },
  {
    id: '3',
    firstName: 'Samuel',
    lastName: 'Mugisha',
    email: 'sam.m@example.com',
    phone: '+250 788 000 003',
    role: 'FIELD_LEADER',
    status: 'ACTIVE',
    churchName: 'Butare University Church',
    zoneName: 'Huye Zone',
    fieldName: 'South Rwanda Field',
    unionName: 'Rwanda Union Mission',
    joinDate: '2005-01-15',
    address: 'Huye, Butare',
    gender: 'MALE',
    dateOfBirth: '1978-07-05',
    activities: generateActivities('3'),
  },
  {
    id: '4',
    firstName: 'Alice',
    lastName: 'Mutoni',
    email: 'alice.m@example.com',
    phone: '+250 788 000 004',
    role: 'MEMBER',
    status: 'INACTIVE',
    churchName: 'Kigali Central Church',
    zoneName: 'Kigali City Zone',
    fieldName: 'Central Rwanda Field',
    unionName: 'Rwanda Union Mission',
    baptismDate: '2018-12-10',
    joinDate: '2019-01-05',
    address: 'Remera, Kigali',
    gender: 'FEMALE',
    dateOfBirth: '1995-05-30',
    activities: generateActivities('4'),
  },
  // Adding more members for pagination testing
  ...Array.from({ length: 20 }, (_, i) => ({
    id: (i + 5).toString(),
    firstName: `Member${i + 5}`,
    lastName: 'SDA',
    email: `member${i + 5}@example.com`,
    phone: `+250 788 000 0${i + 5}`,
    role: 'MEMBER' as const,
    status: 'ACTIVE' as const,
    churchName: i % 2 === 0 ? 'Kigali Central Church' : 'Gisenyi North Church',
    zoneName: i % 2 === 0 ? 'Kigali City Zone' : 'Rubavu Zone',
    fieldName: i % 2 === 0 ? 'Central Rwanda Field' : 'West Rwanda Field',
    unionName: 'Rwanda Union Mission',
    joinDate: '2020-01-01',
    address: 'Kigali, Rwanda',
    gender: i % 2 === 0 ? 'MALE' as const : 'FEMALE' as const,
    dateOfBirth: '1990-01-01',
    activities: [],
  })),
];
